/**
 * ─── MEAL LOG SERVICE ────────────────────────────────────────────────────────
 * Core engine for automatic daily meal tracking and billing calculations.
 * All meal-based billing logic flows through this service.
 *
 * Key responsibilities:
 *   1. Generate daily meal logs for all active users (called once/day or on demand)
 *   2. Backfill logs from a user's start date on creation
 *   3. Calculate monthly bills based on meal log statuses
 *   4. Handle pause period exclusions
 */

const mongoose = require('mongoose');
const MealLog = require('../models/MealLog');
const User = require('../models/User');
const TiffinService = require('../models/TiffinService');
const Bill = require('../models/Bill');
const ApiError = require('../utils/ApiError');
const { getPlan, ACTIVE_MEAL_TYPES } = require('../config/messPlans');

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Normalize a date to midnight (00:00:00.000) UTC for consistent storage.
 */
const normalizeDate = (date) => {
  const d = new Date(date);
  d.setUTCHours(0, 0, 0, 0);
  return d;
};

/**
 * Check if a date falls within a user's pause period.
 */
const isDatePaused = (date, pauseDates = []) => {
  const d = normalizeDate(date);
  return pauseDates.some((pause) => {
    const from = normalizeDate(pause.from);
    const to = pause.to ? normalizeDate(pause.to) : null;
    return d >= from && (to === null || d <= to);
  });
};

/**
 * Get all dates between startDate and endDate (inclusive), normalized to midnight.
 */
const getDateRange = (startDate, endDate) => {
  const dates = [];
  const current = normalizeDate(startDate);
  const end = normalizeDate(endDate);
  while (current <= end) {
    dates.push(new Date(current));
    current.setUTCDate(current.getUTCDate() + 1);
  }
  return dates;
};

const CHARGEABLE_STATUSES = ['pending', 'taken', 'accepted', 'delivered', 'correction_requested'];
// ─────────────────────────────────────────────────────────────────────────────
// 1. BACKFILL — Generate logs from a user's start date up to today
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Called when a new user is created.
 * Generates MealLog documents from messStartDate to today.
 *
 * startSlot:
 *   'morning' → first meal is lunch on messStartDate
 *   'night'   → first meal is dinner on messStartDate (skip lunch on start day)
 *
 * Default status for past dates: 'pending' (assumed taken — "user will get tiffin")
 * Today and future: 'pending'
 */
const generateLogsFromStartDate = async (user) => {
  const startDate = normalizeDate(user.messStartDate || user.planStartDate || new Date());
  const today = normalizeDate(new Date());

  const plan = getPlan(user.planId);
  if (!plan) throw new ApiError(400, `Invalid planId: ${user.planId}`);

  const dates = getDateRange(startDate, today);
  const logsToInsert = [];

  for (const date of dates) {
    const isStartDate = date.getTime() === startDate.getTime();
    const isPaused = isDatePaused(date, user.pauseDates);

    for (const mealType of ACTIVE_MEAL_TYPES) {
      // Skip lunch on start date if startSlot is 'night'
      if (isStartDate && user.messStartSlot === 'night' && mealType === 'lunch') {
        continue;
      }

      const status = isPaused ? 'paused' : 'pending';

      logsToInsert.push({
        userId:         user._id,
        serviceId:      user.serviceId,
        date,
        mealType,
        status,
        planId:         plan.id,
        planName:       plan.name,
        pricePerTiffin: plan.pricePerTiffin,
        isAutoGenerated: true,
        generatedAt:    new Date(),
      });
    }
  }

  if (logsToInsert.length === 0) return { insertedCount: 0 };

  // Use insertMany with ordered:false to skip duplicates gracefully
  try {
    const result = await MealLog.insertMany(logsToInsert, {
      ordered: false,
      rawResult: true,
    });
    return { insertedCount: result.insertedCount || logsToInsert.length };
  } catch (err) {
    // BulkWriteError with code 11000 = duplicate key — safe to ignore
    if (err.code === 11000 || err.name === 'BulkWriteError') {
      const inserted = err.result?.nInserted || 0;
      return { insertedCount: inserted };
    }
    throw err;
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// 2. DAILY GENERATION — Called once per day for an entire service
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate meal logs for ALL active users of a service for a given date.
 * Skips paused users and users whose subscription hasn't started yet.
 * Idempotent — safe to call multiple times for the same date.
 */
const generateDailyLogsForService = async (serviceId, date = new Date()) => {
  const targetDate = normalizeDate(date);

  // Fetch all active users for this service
  const users = await User.find({
    serviceId,
    role: 'user',
    status: 'active',
    subscriptionStatus: 'active',
    messStartDate: { $lte: targetDate },
    planId: { $exists: true, $ne: null },
  });

  let totalInserted = 0;
  const errors = [];

  for (const user of users) {
    const plan = getPlan(user.planId);
    if (!plan) continue;

    const isPaused = isDatePaused(targetDate, user.pauseDates);

    const logsToInsert = ACTIVE_MEAL_TYPES.map((mealType) => ({
      userId:         user._id,
      serviceId,
      date:           targetDate,
      mealType,
      status:         isPaused ? 'paused' : 'pending',
      planId:         plan.id,
      planName:       plan.name,
      pricePerTiffin: plan.pricePerTiffin,
      isAutoGenerated: true,
      generatedAt:    new Date(),
    }));

    try {
      await MealLog.insertMany(logsToInsert, { ordered: false, rawResult: true });
      totalInserted += 2;
    } catch (err) {
      if (err.code === 11000 || err.name === 'BulkWriteError') {
        totalInserted += err.result?.nInserted || 0;
      } else {
        errors.push({ userId: user._id, error: err.message });
      }
    }
  }

  return { totalInserted, userCount: users.length, errors };
};

// ─────────────────────────────────────────────────────────────────────────────
// 3. BILLING CALCULATION — Monthly bill based on MealLogs
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Calculate monthly bill for a user using MealLog records as source of truth.
 *
 * Billing rules:
 *   Charged:     'pending', 'taken', 'accepted', 'delivered', 'correction_requested'
 *   Not charged: 'cancelled', 'rejected', 'missed', 'refunded', 'on_hold', 'skipped', 'paused'
 *   (correction_requested with approved non-taken → not charged after review)
 */
const calculateUserBill = async (userId, serviceId, month, year, generatedBy) => {
  const user = await User.findOne({ _id: userId, serviceId });
  if (!user) throw new ApiError(404, 'User not found in this service');

  const startDate = new Date(year, month - 1, 1);
  startDate.setUTCHours(0, 0, 0, 0);
  const endDate = new Date(year, month, 0, 23, 59, 59, 999);

  const logs = await MealLog.find({
    userId,
    serviceId,
    date: { $gte: startDate, $lte: endDate },
  });

  if (logs.length === 0) {
    throw new ApiError(400, 'No meal logs found for this user in the specified month');
  }

  let totalScheduledDays = 0;
  let takenCount = 0;
  let cancelledCount = 0;
  let skippedCount = 0;
  let pausedCount = 0;
  let correctionCount = 0;
  let baseAmount = 0;
  let deductions = 0;

  // Group by date for "days" counting
  const dateSet = new Set();

  for (const log of logs) {
    const dateKey = log.date.toISOString().split('T')[0];
    const price = log.pricePerTiffin || 0;

    totalScheduledDays++;

    switch (log.status) {
      case 'pending':
      case 'taken':
      case 'accepted':
      case 'delivered':
        takenCount++;
        baseAmount += price;
        dateSet.add(dateKey);
        break;

      case 'correction_requested':
        correctionCount++;
        baseAmount += price; // Charged until correction is approved
        dateSet.add(dateKey);
        break;

      case 'cancelled':
      case 'rejected':
      case 'missed':
      case 'refunded':
        cancelledCount++;
        deductions += 0; // Not charged — do not add to base
        break;

      case 'skipped':
      case 'on_hold':
        skippedCount++;
        break;

      case 'paused':
        pausedCount++;
        break;

      default:
        break;
    }
  }

  const totalAmount = baseAmount;
  const deliveredDays = dateSet.size;

  // Upsert the Bill document
  const bill = await Bill.findOneAndUpdate(
    { userId, serviceId, month, year },
    {
      totalScheduledDays,
      deliveredDays,
      cancelledDays: cancelledCount,
      missedDays: skippedCount,
      extraTiffins: 0,
      baseAmount,
      deductions,
      additions: 0,
      totalAmount,
      generatedBy,
      status: 'pending',
      notes: `Auto-calculated from ${logs.length} meal logs. Paused: ${pausedCount}, Corrections: ${correctionCount}`,
    },
    { new: true, upsert: true }
  );

  return bill;
};

// ─────────────────────────────────────────────────────────────────────────────
// 4. CANCEL FUTURE LOGS — On cancellation approval
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Mark all MealLogs for a user from effectiveDate onward as 'cancelled'.
 * Called when owner approves a subscription cancellation.
 */
const cancelFutureLogs = async (userId, serviceId, effectiveDate) => {
  const from = normalizeDate(effectiveDate);
  const result = await MealLog.updateMany(
    {
      userId,
      serviceId,
      date: { $gte: from },
      status: { $in: ['pending', 'taken'] },
    },
    { $set: { status: 'cancelled' } }
  );
  return result.modifiedCount;
};

// ─────────────────────────────────────────────────────────────────────────────
// 5. PAUSE LOGS — Mark a date range as paused
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Mark all MealLogs within a pause date range as 'paused'.
 */
const pauseLogs = async (userId, serviceId, fromDate, toDate) => {
  const from = normalizeDate(fromDate);
  const to = normalizeDate(toDate);
  const result = await MealLog.updateMany(
    {
      userId,
      serviceId,
      date: { $gte: from, $lte: to },
      status: { $in: ['pending'] },
    },
    { $set: { status: 'paused' } }
  );
  return result.modifiedCount;
};

// ─────────────────────────────────────────────────────────────────────────────
// 6. GET USER MEAL HISTORY — Paginated
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetch paginated meal history for a user.
 * @param {string} userId
 * @param {object} options - { from, to, page, limit, mealType }
 */
const getUserMealHistory = async (userId, options = {}) => {
  const {
    from,
    to,
    page = 1,
    limit = 60,
    mealType,
  } = options;

  const filter = { userId };
  if (from || to) {
    filter.date = {};
    if (from) filter.date.$gte = normalizeDate(from);
    if (to)   filter.date.$lte = normalizeDate(to);
  }
  if (mealType) filter.mealType = mealType;

  const skip = (page - 1) * limit;

  const [logs, total] = await Promise.all([
    MealLog.find(filter)
      .sort({ date: -1, mealType: 1 })
      .skip(skip)
      .limit(limit)
      .lean(),
    MealLog.countDocuments(filter),
  ]);

  return { logs, total, page, limit, pages: Math.ceil(total / limit) };
};
// // new /**
//  * Get meal summary aggregated by user and date for a given service.
//  * @param {ObjectId} serviceId
//  * @param {Object} options - { userId, search, from, to, page, limit }
//  * @returns {Object} { usersSummary, totals, pagination }
//  */

const getMealSummary = async (serviceId, options = {}) => {
  const {
    userId,
    search,
    from,
    to,
    page = 1,
    limit = 20
  } = options;

  const pageNum = Number(page) || 1;
  const limitNum = Number(limit) || 20;

  if (!mongoose.Types.ObjectId.isValid(serviceId)) {
    throw new ApiError(400, 'Invalid service ID');
  }

  const startDate = from
    ? normalizeDate(from)
    : normalizeDate(new Date());

  const endDate = to
    ? normalizeDate(to)
    : startDate;

  const baseMatch = {
    serviceId: new mongoose.Types.ObjectId(serviceId),
    date: {
      $gte: startDate,
      $lte: endDate
    },
    mealType: {
      $in: ['lunch', 'dinner']
    }
  };

  let userIds = [];

  // -------------------------------------------------
  // Determine users to include
  // -------------------------------------------------
  if (userId) {
    if (!mongoose.Types.ObjectId.isValid(userId)) {
      throw new ApiError(400, 'Invalid user ID');
    }

    const user = await User.findById(userId)
      .select('_id')
      .lean();

    if (!user) {
      throw new ApiError(404, 'User not found');
    }

    userIds = [user._id];
  } else if (search) {
    const matchedUsers = await User.find({
      serviceId: new mongoose.Types.ObjectId(serviceId),
      role: 'user',
      $or: [
        {
          name: {
            $regex: search,
            $options: 'i'
          }
        },
        {
          userId: {
            $regex: search,
            $options: 'i'
          }
        }
      ]
    })
      .select('_id')
      .lean();

    userIds = matchedUsers.map(user => user._id);
  } else {
    userIds = await MealLog.distinct('userId', {
      serviceId: new mongoose.Types.ObjectId(serviceId),
      date: {
        $gte: startDate,
        $lte: endDate
      }
    });
  }

  // -------------------------------------------------
  // No users found
  // -------------------------------------------------
  if (!userIds.length) {
    return {
      usersSummary: [],
      totals: {
        totalLunch: 0,
        totalDinner: 0,
        totalMeals: 0,
        totalAmount: 0
      },
      pagination: {
        total: 0,
        page: pageNum,
        pages: 0
      }
    };
  }

  // -------------------------------------------------
  // Overall totals (Strictly based on Delivered meals)
  // -------------------------------------------------
  const [totalsResult] = await MealLog.aggregate([
    {
      $match: {
        ...baseMatch,
        userId: {
          $in: userIds
        }
      }
    },
    {
      $group: {
        _id: null,
        totalLunch: {
          $sum: {
            $cond: [
              {
                $and: [
                  { $eq: ['$mealType', 'lunch'] },
                  { $in: ['$status', ['taken', 'accepted', 'delivered']] }
                ]
              },
              1,
              0
            ]
          }
        },
        totalDinner: {
          $sum: {
            $cond: [
              {
                $and: [
                  { $eq: ['$mealType', 'dinner'] },
                  { $in: ['$status', ['taken', 'accepted', 'delivered']] }
                ]
              },
              1,
              0
            ]
          }
        },
        totalAmount: {
          $sum: {
            $cond: [
              { $in: ['$status', ['taken', 'accepted', 'delivered']] },
              '$pricePerTiffin',
              0
            ]
          }
        }
      }
    }
  ]);

  const totalLunch = totalsResult?.totalLunch || 0;
  const totalDinner = totalsResult?.totalDinner || 0;
  const totalAmount = totalsResult?.totalAmount || 0;

  // -------------------------------------------------
  // Paginated Results
  // -------------------------------------------------
  let usersSummary = [];
  let totalCount = 0;

  if (userId) {
    // Single User Detail View - Aggregate by Date
    const aggregation = await MealLog.aggregate([
      {
        $match: {
          ...baseMatch,
          userId: new mongoose.Types.ObjectId(userId)
        }
      },
      {
        $group: {
          _id: {
            $dateToString: {
              format: '%Y-%m-%d',
              date: '$date'
            }
          },
          lunchStatus: {
            $max: {
              $cond: [
                { $eq: ['$mealType', 'lunch'] },
                '$status',
                null
              ]
            }
          },
          dinnerStatus: {
            $max: {
              $cond: [
                { $eq: ['$mealType', 'dinner'] },
                '$status',
                null
              ]
            }
          },
          lunchPrice: {
            $max: {
              $cond: [
                { $eq: ['$mealType', 'lunch'] },
                '$pricePerTiffin',
                0
              ]
            }
          },
          dinnerPrice: {
            $max: {
              $cond: [
                { $eq: ['$mealType', 'dinner'] },
                '$pricePerTiffin',
                0
              ]
            }
          }
        }
      },
      {
        $sort: {
          '_id': -1
        }
      }
    ]);

    totalCount = aggregation.length;
    const skip = (pageNum - 1) * limitNum;
    const pagedAggregation = aggregation.slice(skip, skip + limitNum);

    const user = await User.findById(userId)
      .select('name userId phone')
      .lean();

    usersSummary = pagedAggregation.map(item => {
      const lunchDelivered = ['taken', 'accepted', 'delivered'].includes(item.lunchStatus);
      const dinnerDelivered = ['taken', 'accepted', 'delivered'].includes(item.dinnerStatus);
      return {
        userId: userId,
        employeeId: user?.userId || '',
        userName: user?.name || 'Unknown',
        userPhone: user?.phone || '',
        date: item._id,
        lunchStatus: item.lunchStatus,
        dinnerStatus: item.dinnerStatus,
        lunchDelivered,
        dinnerDelivered,
        amount: (lunchDelivered ? item.lunchPrice : 0) + (dinnerDelivered ? item.dinnerPrice : 0)
      };
    });
  } else {
    // All Users List View - Aggregate by User
    const totalUsers = userIds.length;
    const skip = (pageNum - 1) * limitNum;
    const pagedUserIds = userIds.slice(skip, skip + limitNum);

    const aggregation = await MealLog.aggregate([
      {
        $match: {
          ...baseMatch,
          userId: { $in: pagedUserIds }
        }
      },
      {
        $group: {
          _id: '$userId',
          lunchCount: {
            $sum: {
              $cond: [
                {
                  $and: [
                    { $eq: ['$mealType', 'lunch'] },
                    { $in: ['$status', ['taken', 'accepted', 'delivered']] }
                  ]
                },
                1,
                0
              ]
            }
          },
          dinnerCount: {
            $sum: {
              $cond: [
                {
                  $and: [
                    { $eq: ['$mealType', 'dinner'] },
                    { $in: ['$status', ['taken', 'accepted', 'delivered']] }
                  ]
                },
                1,
                0
              ]
            }
          },
          amount: {
            $sum: {
              $cond: [
                { $in: ['$status', ['taken', 'accepted', 'delivered']] },
                '$pricePerTiffin',
                0
              ]
            }
          }
        }
      }
    ]);

    const users = await User.find({
      _id: { $in: pagedUserIds }
    })
      .select('name userId phone')
      .lean();

    const usersMap = {};
    users.forEach(user => {
      usersMap[user._id.toString()] = user;
    });

    usersSummary = aggregation.map(item => {
      const user = usersMap[item._id.toString()];
      return {
        userId: item._id,
        employeeId: user?.userId || '',
        userName: user?.name || 'Unknown',
        userPhone: user?.phone || '',
        lunchCount: item.lunchCount,
        dinnerCount: item.dinnerCount,
        amount: item.amount
      };
    });

    totalCount = totalUsers;
  }

  return {
    usersSummary,
    totals: {
      totalLunch,
      totalDinner,
      totalMeals: totalLunch + totalDinner,
      totalAmount
    },
    pagination: {
      total: totalCount,
      page: pageNum,
      pages: Math.ceil(totalCount / limitNum),
      limit: limitNum
    }
  };
};

module.exports = {
  generateLogsFromStartDate,
  generateDailyLogsForService,
  calculateUserBill,
  cancelFutureLogs,
  pauseLogs,
  getUserMealHistory,
  normalizeDate,
  isDatePaused,
  getMealSummary
};
