const mongoose = require('mongoose');

/**
 * MealLog — Daily automatic meal tracking record.
 * One document per user per date per meal type.
 * Generated automatically when a user is created (backfill) and daily thereafter.
 *
 * Status flow:
 *   pending            → Default: meal assumed delivered/taken
 *   taken              → Explicitly confirmed as taken
 *   cancelled          → User requested + owner approved cancellation for this meal
 *   skipped            → Owner marked as skipped (e.g., user was away, meal not sent)
 *   paused             → Subscription is paused for this date
 *   correction_requested → User raised a correction on this entry
 *
 * Billing rule:
 *   Charged:     pending, taken, correction_requested (until approved)
 *   Not charged: cancelled, skipped, paused, (correction approved to non-taken)
 */
const correctionRequestSchema = new mongoose.Schema(
  {
    reason:           { type: String, trim: true, required: true },
    requestedStatus:  {
      type: String,
      enum: ['taken', 'cancelled', 'skipped'],
      required: true,
    }, // What the user believes the correct status should be
    requestedAt:      { type: Date, default: Date.now },
    status: {
      type: String,
      enum: ['pending', 'approved', 'rejected'],
      default: 'pending',
    },
    reviewedBy:       { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    reviewedAt:       { type: Date },
    reviewNote:       { type: String, trim: true },
    menuId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Menu',
    },
    // If user requested a correction for this log
    correctionReason: { type: String, trim: true },
    requestedStatus: { type: String, enum: ['taken', 'cancelled', 'skipped'] },
    correctionStatus: { type: String, enum: ['pending', 'approved', 'rejected'] },
    ownerNote: { type: String, trim: true }, // For admin comments on corrections or general
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

const mealLogSchema = new mongoose.Schema(
  {
    // ── Core References ───────────────────────────────────────────────────────
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    serviceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'TiffinService',
      required: true,
      index: true,
    },

    // ── Meal Identity ─────────────────────────────────────────────────────────
    date: {
      type: Date,
      required: true,
    },
    mealType: {
      type: String,
      enum: ['lunch', 'dinner'],
      required: true,
    },

    // ── Status ────────────────────────────────────────────────────────────────
    status: {
      type: String,
      enum: [
        'pending',             // Generated; assumed taken until changed
        'taken',               // Explicitly confirmed taken
        'accepted',            // Owner confirmed this order
        'delivered',           // Meal delivered to user
        'cancelled',           // Cancelled (user req approved or owner cancelled)
        'skipped',             // Not delivered (owner marked)
        'paused',              // Within a pause period
        'on_hold',             // Temporarily on hold
        'rejected',            // Owner rejected this meal
        'missed',              // User was absent, meal not delivered
        'refunded',            // Refund processed for this meal
        'correction_requested', // User raised correction
      ],
      default: 'pending',
    },

    // ── Plan Snapshot (at time of generation) ─────────────────────────────────
    planId:          { type: String }, // e.g. 'plan_1'
    planName:        { type: String }, // e.g. 'Basic Plan'
    pricePerTiffin:  { type: Number, default: 0 },

    // ── Correction Request ────────────────────────────────────────────────────
    correctionRequest: correctionRequestSchema,

    // ── Metadata ──────────────────────────────────────────────────────────────
    isAutoGenerated:  { type: Boolean, default: true },
    generatedAt:      { type: Date, default: Date.now },
    updatedBy:        { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    notes:            { type: String, trim: true },
  },
  { timestamps: true }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// Unique constraint: one log per user per date per meal type
mealLogSchema.index({ userId: 1, date: 1, mealType: 1 }, { unique: true });
// Fast service-level daily queries (owner dashboard)
mealLogSchema.index({ serviceId: 1, date: 1 });
// Fast user history queries with date range
mealLogSchema.index({ userId: 1, date: -1 });
// Correction review queue for owners
mealLogSchema.index({ serviceId: 1, 'correctionRequest.status': 1 });

// ── Virtual: Is this meal charged? ────────────────────────────────────────────
mealLogSchema.virtual('isCharged').get(function () {
  return ['pending', 'taken', 'accepted', 'delivered', 'correction_requested'].includes(this.status);
});

// ── Virtual: Charge amount ────────────────────────────────────────────────────
mealLogSchema.virtual('chargeAmount').get(function () {
  return this.isCharged ? this.pricePerTiffin : 0;
});

module.exports = mongoose.model('MealLog', mealLogSchema);
